use std::fmt;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Keyword {
    Def,
    Theorem,
    Lemma,
    Abbrev,
    Example,
    Instance,
    Axiom,
    Opaque,
    Structure,
    Class,
    Inductive,
    Where,
    Extends,
    Deriving,
    Private,
    Protected,
    Noncomputable,
    Unsafe,
    Partial,
    Nonrec,
    Namespace,
    Module,
    Section,
    End,
    Open,
    Variable,
    Universe,
    Import,
    Mutual,
    In,
    Export,
    Fun,
    Let,
    Have,
    Match,
    If,
    Then,
    Else,
    Do,
    By,
    Return,
    Show,
    Suffices,
    Assume,
    With,
    Nomatch,
    Nofun,
    Sort,
    Type,
    Prop,
    True,
    False,
    Sorry,
    Forall,
    Exists,
    SetOption,
    Attribute,
    Check,
    Eval,
    Print,
    Reduce,
    Synth,
    Exit,
    Prelude,
    Initialize,
    BuiltinInitialize,
    Macro,
    Syntax,
    Elab,
    Notation,
    Prefix,
    Infix,
    Infixl,
    Infixr,
    Postfix,
    For,
    While,
    Repeat,
    Unless,
    Try,
    Catch,
    Finally,
    Throw,
    Pure,
    At,
}

impl Keyword {
    pub fn from_str(s: &str) -> Option<Keyword> {
        match s {
            "def" => Some(Self::Def),
            "theorem" => Some(Self::Theorem),
            "lemma" => Some(Self::Lemma),
            "abbrev" => Some(Self::Abbrev),
            "example" => Some(Self::Example),
            "instance" => Some(Self::Instance),
            "axiom" => Some(Self::Axiom),
            "opaque" => Some(Self::Opaque),
            "structure" => Some(Self::Structure),
            "class" => Some(Self::Class),
            "inductive" => Some(Self::Inductive),
            "where" => Some(Self::Where),
            "extends" => Some(Self::Extends),
            "deriving" => Some(Self::Deriving),
            "private" => Some(Self::Private),
            "protected" => Some(Self::Protected),
            "noncomputable" => Some(Self::Noncomputable),
            "unsafe" => Some(Self::Unsafe),
            "partial" => Some(Self::Partial),
            "nonrec" => Some(Self::Nonrec),
            "namespace" => Some(Self::Namespace),
            "module" => Some(Self::Module),
            "section" => Some(Self::Section),
            "end" => Some(Self::End),
            "open" => Some(Self::Open),
            "variable" => Some(Self::Variable),
            "universe" => Some(Self::Universe),
            "import" => Some(Self::Import),
            "mutual" => Some(Self::Mutual),
            "in" => Some(Self::In),
            "export" => Some(Self::Export),
            "fun" => Some(Self::Fun),
            "let" => Some(Self::Let),
            "have" => Some(Self::Have),
            "match" => Some(Self::Match),
            "if" => Some(Self::If),
            "then" => Some(Self::Then),
            "else" => Some(Self::Else),
            "do" => Some(Self::Do),
            "by" => Some(Self::By),
            "return" => Some(Self::Return),
            "show" => Some(Self::Show),
            "suffices" => Some(Self::Suffices),
            "assume" => Some(Self::Assume),
            "with" => Some(Self::With),
            "nomatch" => Some(Self::Nomatch),
            "nofun" => Some(Self::Nofun),
            "sort" => Some(Self::Sort),
            "Type" => Some(Self::Type),
            "Prop" => Some(Self::Prop),
            "true" => Some(Self::True),
            "false" => Some(Self::False),
            "sorry" => Some(Self::Sorry),
            "forall" => Some(Self::Forall),
            "exists" => Some(Self::Exists),
            "set_option" => Some(Self::SetOption),
            "attribute" => Some(Self::Attribute),
            "#check" => Some(Self::Check),
            "#eval" => Some(Self::Eval),
            "#print" => Some(Self::Print),
            "#reduce" => Some(Self::Reduce),
            "#synth" => Some(Self::Synth),
            "#exit" => Some(Self::Exit),
            "prelude" => Some(Self::Prelude),
            "initialize" => Some(Self::Initialize),
            "builtin_initialize" => Some(Self::BuiltinInitialize),
            "macro" => Some(Self::Macro),
            "syntax" => Some(Self::Syntax),
            "elab" => Some(Self::Elab),
            "notation" => Some(Self::Notation),
            "prefix" => Some(Self::Prefix),
            "infix" => Some(Self::Infix),
            "infixl" => Some(Self::Infixl),
            "infixr" => Some(Self::Infixr),
            "postfix" => Some(Self::Postfix),
            "for" => Some(Self::For),
            "while" => Some(Self::While),
            "repeat" => Some(Self::Repeat),
            "unless" => Some(Self::Unless),
            "try" => Some(Self::Try),
            "catch" => Some(Self::Catch),
            "finally" => Some(Self::Finally),
            "throw" => Some(Self::Throw),
            "pure" => Some(Self::Pure),
            "@" => Some(Self::At),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Def => "def",
            Self::Theorem => "theorem",
            Self::Lemma => "lemma",
            Self::Abbrev => "abbrev",
            Self::Example => "example",
            Self::Instance => "instance",
            Self::Axiom => "axiom",
            Self::Opaque => "opaque",
            Self::Structure => "structure",
            Self::Class => "class",
            Self::Inductive => "inductive",
            Self::Where => "where",
            Self::Extends => "extends",
            Self::Deriving => "deriving",
            Self::Private => "private",
            Self::Protected => "protected",
            Self::Noncomputable => "noncomputable",
            Self::Unsafe => "unsafe",
            Self::Partial => "partial",
            Self::Nonrec => "nonrec",
            Self::Namespace => "namespace",
            Self::Module => "module",
            Self::Section => "section",
            Self::End => "end",
            Self::Open => "open",
            Self::Variable => "variable",
            Self::Universe => "universe",
            Self::Import => "import",
            Self::Mutual => "mutual",
            Self::In => "in",
            Self::Export => "export",
            Self::Fun => "fun",
            Self::Let => "let",
            Self::Have => "have",
            Self::Match => "match",
            Self::If => "if",
            Self::Then => "then",
            Self::Else => "else",
            Self::Do => "do",
            Self::By => "by",
            Self::Return => "return",
            Self::Show => "show",
            Self::Suffices => "suffices",
            Self::Assume => "assume",
            Self::With => "with",
            Self::Nomatch => "nomatch",
            Self::Nofun => "nofun",
            Self::Sort => "sort",
            Self::Type => "Type",
            Self::Prop => "Prop",
            Self::True => "true",
            Self::False => "false",
            Self::Sorry => "sorry",
            Self::Forall => "forall",
            Self::Exists => "exists",
            Self::SetOption => "set_option",
            Self::Attribute => "attribute",
            Self::Check => "#check",
            Self::Eval => "#eval",
            Self::Print => "#print",
            Self::Reduce => "#reduce",
            Self::Synth => "#synth",
            Self::Exit => "#exit",
            Self::Prelude => "prelude",
            Self::Initialize => "initialize",
            Self::BuiltinInitialize => "builtin_initialize",
            Self::Macro => "macro",
            Self::Syntax => "syntax",
            Self::Elab => "elab",
            Self::Notation => "notation",
            Self::Prefix => "prefix",
            Self::Infix => "infix",
            Self::Infixl => "infixl",
            Self::Infixr => "infixr",
            Self::Postfix => "postfix",
            Self::For => "for",
            Self::While => "while",
            Self::Repeat => "repeat",
            Self::Unless => "unless",
            Self::Try => "try",
            Self::Catch => "catch",
            Self::Finally => "finally",
            Self::Throw => "throw",
            Self::Pure => "pure",
            Self::At => "@",
        }
    }
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}
